#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemSchool.DataLibrary
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;
    using System.Data.Entity;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SisSchoolDb")]
	public partial class SisSchoolContextDataContext: DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertInscripccion(Inscripccion instance);
    partial void UpdateInscripccion(Inscripccion instance);
    partial void DeleteInscripccion(Inscripccion instance);

        internal DbSet<object> Set<T>()
        {
            throw new NotImplementedException();
        }
        #endregion

        public SisSchoolContextDataContext() : 
				base(System.Configuration.ConfigurationManager.ConnectionStrings["SisSchoolDbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SisSchoolContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SisSchoolContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        internal object Entry<TEntity>(TEntity entityToDelete) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public SisSchoolContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SisSchoolContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Inscripccion> Inscripccions
		{
			get
			{
				return this.GetTable<Inscripccion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inscripccion")]
	public partial class Inscripccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEstudiante;
		
		private string _Nombres_;
		
		private string _Apellido1_;
		
		private string _Apellido2_;
		
		private string _Direccion_;
		
		private string _Telefono_;
		
		private string _Foto;
		
		private System.Data.Linq.Binary _ActaNacimiento_;
		
		private System.Data.Linq.Binary _CertificadoMedico_;
		
		private string _Estado_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEstudianteChanging(int value);
    partial void OnIdEstudianteChanged();
    partial void OnNombres_Changing(string value);
    partial void OnNombres_Changed();
    partial void OnApellido1_Changing(string value);
    partial void OnApellido1_Changed();
    partial void OnApellido2_Changing(string value);
    partial void OnApellido2_Changed();
    partial void OnDireccion_Changing(string value);
    partial void OnDireccion_Changed();
    partial void OnTelefono_Changing(string value);
    partial void OnTelefono_Changed();
    partial void OnFotoChanging(string value);
    partial void OnFotoChanged();
    partial void OnActaNacimiento_Changing(System.Data.Linq.Binary value);
    partial void OnActaNacimiento_Changed();
    partial void OnCertificadoMedico_Changing(System.Data.Linq.Binary value);
    partial void OnCertificadoMedico_Changed();
    partial void OnEstado_Changing(string value);
    partial void OnEstado_Changed();
    #endregion
		
		public Inscripccion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstudiante", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEstudiante
		{
			get
			{
				return this._IdEstudiante;
			}
			set
			{
				if ((this._IdEstudiante != value))
				{
					this.OnIdEstudianteChanging(value);
					this.SendPropertyChanging();
					this._IdEstudiante = value;
					this.SendPropertyChanged("IdEstudiante");
					this.OnIdEstudianteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombres ]", Storage="_Nombres_", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombres_
		{
			get
			{
				return this._Nombres_;
			}
			set
			{
				if ((this._Nombres_ != value))
				{
					this.OnNombres_Changing(value);
					this.SendPropertyChanging();
					this._Nombres_ = value;
					this.SendPropertyChanged("Nombres_");
					this.OnNombres_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Apellido1 ]", Storage="_Apellido1_", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Apellido1_
		{
			get
			{
				return this._Apellido1_;
			}
			set
			{
				if ((this._Apellido1_ != value))
				{
					this.OnApellido1_Changing(value);
					this.SendPropertyChanging();
					this._Apellido1_ = value;
					this.SendPropertyChanged("Apellido1_");
					this.OnApellido1_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Apellido2 ]", Storage="_Apellido2_", DbType="VarChar(30)")]
		public string Apellido2_
		{
			get
			{
				return this._Apellido2_;
			}
			set
			{
				if ((this._Apellido2_ != value))
				{
					this.OnApellido2_Changing(value);
					this.SendPropertyChanging();
					this._Apellido2_ = value;
					this.SendPropertyChanged("Apellido2_");
					this.OnApellido2_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Direccion ]", Storage="_Direccion_", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Direccion_
		{
			get
			{
				return this._Direccion_;
			}
			set
			{
				if ((this._Direccion_ != value))
				{
					this.OnDireccion_Changing(value);
					this.SendPropertyChanging();
					this._Direccion_ = value;
					this.SendPropertyChanged("Direccion_");
					this.OnDireccion_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Telefono ]", Storage="_Telefono_", DbType="VarChar(15)")]
		public string Telefono_
		{
			get
			{
				return this._Telefono_;
			}
			set
			{
				if ((this._Telefono_ != value))
				{
					this.OnTelefono_Changing(value);
					this.SendPropertyChanging();
					this._Telefono_ = value;
					this.SendPropertyChanged("Telefono_");
					this.OnTelefono_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarChar(20)")]
		public string Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ActaNacimiento ]", Storage="_ActaNacimiento_", DbType="Binary(1) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ActaNacimiento_
		{
			get
			{
				return this._ActaNacimiento_;
			}
			set
			{
				if ((this._ActaNacimiento_ != value))
				{
					this.OnActaNacimiento_Changing(value);
					this.SendPropertyChanging();
					this._ActaNacimiento_ = value;
					this.SendPropertyChanged("ActaNacimiento_");
					this.OnActaNacimiento_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CertificadoMedico ]", Storage="_CertificadoMedico_", DbType="Binary(1) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary CertificadoMedico_
		{
			get
			{
				return this._CertificadoMedico_;
			}
			set
			{
				if ((this._CertificadoMedico_ != value))
				{
					this.OnCertificadoMedico_Changing(value);
					this.SendPropertyChanging();
					this._CertificadoMedico_ = value;
					this.SendPropertyChanged("CertificadoMedico_");
					this.OnCertificadoMedico_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Estado ]", Storage="_Estado_", DbType="VarChar(8)")]
		public string Estado_
		{
			get
			{
				return this._Estado_;
			}
			set
			{
				if ((this._Estado_ != value))
				{
					this.OnEstado_Changing(value);
					this.SendPropertyChanging();
					this._Estado_ = value;
					this.SendPropertyChanged("Estado_");
					this.OnEstado_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
